version: '3.8'

services:

  api:
    image: node:12-slim
    container_name: api
    restart: unless-stopped
    working_dir: /usr/src/app
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      # - node_modules:/usr/src/app/node_modules
    env_file: .envrc
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    networks:
      - project-network
    command: bash -c "yarn && yarn develop:debug"

  db:
    image: postgres:alpine
    container_name: 'pgsql'
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file: .envrc
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - project-network

  adminer:
    image: adminer
    container_name: 'adminer'
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${DATABASE_ADMIN_PORT}:${DATABASE_ADMIN_PORT}
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  dbdata:
  # node_modules:
